#
# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
#
# This configuration omits values that are correct in their default state.
#

project_id = "eplan"

[auth.sms]
enable_signup = false

[auth.mfa.totp]
enroll_enabled = false
verify_enabled = false

[db.seed]
enabled = false

[realtime]
enabled = false

[storage]
enabled = false

[edge_runtime]
enabled = false

[inbucket]
enabled = false

[analytics]
# Explicitly set to false to avoid specific errors, despite being the default.
enabled = false
