import { CompanyDTO } from "@/app/v2/features/company/types"

export const fetchCompanies = async (): Promise<CompanyDTO[]> => {
  // Fake a delay to simulate an API call
  await new Promise((resolve) => setTimeout(resolve, 200))

  return [
    { id: 1, name: "Company A" },
    { id: 2, name: "Company B" },
    { id: 3, name: "Company C" },
    { id: 4, name: "Company D" },
    { id: 5, name: "Company E" },
    { id: 6, name: "Company F" },
    { id: 7, name: "Company G" },
    { id: 8, name: "Company H" },
    { id: 9, name: "Company I" },
    { id: 10, name: "Company J" },
    { id: 11, name: "Company K" },
    { id: 12, name: "Company L" },
    { id: 13, name: "Company M" },
    { id: 14, name: "Company N" },
    { id: 15, name: "Company O" },
    { id: 16, name: "Company P" },
    { id: 17, name: "Company Q" },
    { id: 18, name: "Company R" },
    { id: 19, name: "Company S" },
    { id: 20, name: "Company T" },
    { id: 21, name: "Company U" },
    { id: 22, name: "Company V" },
    { id: 23, name: "Company W" },
    { id: 24, name: "Company X" },
    { id: 25, name: "Company Y" },
    { id: 26, name: "Company Z" },
    { id: 27, name: "Company AA" },
    { id: 28, name: "Company AB" },
    { id: 29, name: "Company AC" },
    { id: 30, name: "Company AD" },
    { id: 31, name: "Company AE" },
    { id: 32, name: "Company AF" },
    { id: 33, name: "Company AG" },
    { id: 34, name: "Company AH" },
    { id: 35, name: "Company AI" },
    { id: 36, name: "Company AJ" },
    { id: 37, name: "Company AK" },
    { id: 38, name: "Company AL" },
    { id: 39, name: "Company AM" },
    { id: 40, name: "Company AN" },
    { id: 41, name: "Company AO" },
    { id: 42, name: "Company AP" },
    { id: 43, name: "Company AQ" },
    { id: 44, name: "Company AR" },
    { id: 45, name: "Company AS" },
    { id: 46, name: "Company AT" },
    { id: 47, name: "Company AU" },
    { id: 48, name: "Company AV" },
    { id: 49, name: "Company AW" },
    { id: 50, name: "Company AX" },
    { id: 51, name: "Company AY" },
    { id: 52, name: "Company AZ" },
    { id: 53, name: "Company BA" },
    { id: 54, name: "Company BB" },
    { id: 55, name: "Company BC" },
    { id: 56, name: "Company BD" },
    { id: 57, name: "Company BE" },
    { id: 58, name: "Company BF" },
    { id: 59, name: "Company BG" },
    { id: 60, name: "Company BH" },
    { id: 61, name: "Company BI" },
    { id: 62, name: "Company BJ" },
    { id: 63, name: "Company BK" },
    { id: 64, name: "Company BL" },
    { id: 65, name: "Company BM" },
    { id: 66, name: "Company BN" },
    { id: 67, name: "Company BO" },
    { id: 68, name: "Company BP" },
    { id: 69, name: "Company BQ" },
    { id: 70, name: "Company BR" },
    { id: 71, name: "Company BS" },
    { id: 72, name: "Company BT" },
    { id: 73, name: "Company BU" },
    { id: 74, name: "Company BV" },
    { id: 75, name: "Company BW" },
    { id: 76, name: "Company BX" },
    { id: 77, name: "Company BY" },
    { id: 78, name: "Company BZ" },
  ]
}
